-- BUSINESS QUESTIONS: 
-- Advanced Analysis 
----------------------------

/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/
-- SALE VALUE = QUANTITY * PRICE_PER_UNIT
-- add total_price column name in Ordder_items table
alter table order_items
add column total_price float;
update order_items set total_price = price_per_unit * quantity;
select * from order_items

-- Solving the challenge

SELECT p.product_id, p.product_name, sum(oi.quantity) as total_quantity,  sum(oi.total_price) as Total_revenue 
FROM PRODUCTS P 
JOIN ORDER_ITEMS OI ON OI.PRODUCT_ID = P.PRODUCT_ID 
group by 1,2
order by 3 DESC
limit 10

/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/
select * from orders
select * from order_items
select * from products
select * from category
--perentage of category contribution: category_name / sum (total_revenue) * 100
SELECT 
p.category_id, c.category_name, sum(oi.total_price) as total_revenue,
sum(oi.total_price)::numeric / (select  sum (total_price) from order_items)::numeric * 100 as Contribution
FROM order_items oi 
left join products p on oi.product_id = p.product_id
left join category c on c.category_id = p.category_id
group by 1,2

/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only order with more than 10 orders
*/
-- aov :  total orders value or amount /  number of orders
select * from customers
select * from order_items 
select * from orders

with t1 as (
select o.customer_id, concat(c.first_name, ' ',c.last_name) as Full_name, count(o.order_id) as Total_orders,
sum(oi.total_price) as Order_amount , sum(oi.total_price) / count(o.order_id) as AOV
from order_items oi
join orders  o on o.order_id = oi.order_id
left join customers c on c.customer_id = o.customer_id
group by 1,2
)
select * 
from t1
where total_orders>10
/*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!
*/ 
-- Tables order, order_items, group by , 
--master-table
select * from order_items oi
join orders o on o.order_id = oi.order_id
----------
with t1 as(
select  
	extract(month from o.order_date) as month, 
	extract(year from order_date) as year, 
	sum(oi.total_price) as total_revenue 
from order_items oi
join orders o on o.order_id = oi.order_id
where o.order_date >= current_date - interval '3 year'
group by 1,2 order by 1,2
)
select year, month, total_revenue as current_month_sale,lag(total_revenue,1) over(order by year, month) as last_month_sale from t1

/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
Challenge: List customer details and the time since their registration.
*/
select * from customers 
select * from orders
-- The list of customers who have not placed any order
select c.customer_id, concat(c.first_name, ' ' ,c.last_name) as Full_name, 
from customers c
left join orders o  on c.customer_id = o.customer_id
where o.customer_id is null
-- Time of fist order for each customer
SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS full_name,
    AGE(CURRENT_DATE, MIN(o.order_date)) AS time_since_registration
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY 1, 2;

/*
6. Least-Selling Categories by State
Identify the least-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/
select * from category
select * from products
select * from order_items
select * from customers

select * from order_items as oi
join orders o on o.order_id = oi.order_id 
join products p on p.product_id = oi.product_id
join category c on c.category_id = p.category_id
join customers cu on cu.customer_id = o.customer_id
--Identify the least-selling product category for each state, alongwith total sales:
with t1 as(
select cu.state, c.category_id, c.category_name, sum(oi.quantity) as Quantity_sold,
round(sum(oi.total_price)::numeric,2) as Total_Revenue,
rank() over(partition by cu.state order by sum(oi.quantity)) as rank
from order_items as oi
join orders o on o.order_id = oi.order_id 
join products p on p.product_id = oi.product_id
join category c on c.category_id = p.category_id
join customers cu on cu.customer_id = o.customer_id
group by 1,2,3 ) select state, category_name, Total_Revenue from t1 where rank = 1

/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/
select * from customers
select * from order_items
select * from orders
-------
select * from customers c
join orders o on o.customer_id = c.customer_id
join order_items oi on oi.order_id = o.order_id 
-------
with t1 as(
select concat(first_name, ' ', last_name) as Full_name, round(sum(total_price)::numeric,2) as total_revenue
from customers c
join orders o on o.customer_id = c.customer_id
join order_items oi on oi.order_id = o.order_id 
group by 1 order by 2 desc
)
select Full_name, Total_revenue, dense_rank() over(order by total_revenue ) as rank
from t1

/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/
select * from inventory
select * from products
-----
select * from inventory i
join products p on i.product_id = p.product_id 
-----
select warehouse_id, p.product_name, i.stock, i.last_stock_date from inventory i
join products p on i.product_id = p.product_id 
where i.stock <= 10
/*
9. Shipping Delays
Identify orders where the shipping date is later than 3 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/
select * from shipping
select * from orders
select * from customers
select * from order_items
----
select * from shipping s
join orders o on o.order_id = s.order_id
join order_items oi on o.order_id = oi.order_id
join customers c on c.customer_id = o.customer_id
----
select concat(first_name, ' ' , last_name) as full_name, order_date, shipping_providers, delivery_status, order_status, quantity, price_per_unit, total_price
from shipping s
join orders o on o.order_id = s.order_id
join order_items oi on o.order_id = oi.order_id
join customers c on c.customer_id = o.customer_id
where shipping_date > order_date +  interval '3 days'

/*
10. Payment Success Rate 
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/
select * from payments
select * from orders
---
select * from payments p
join orders o on p.order_id = o.order_id
---
select p.payment_status, count(*) as count, 
round(count(*)::numeric / (select count(*) from payments)::numeric * 100, 2) as percentage
from payments p
join orders o on p.order_id = o.order_id
group by 1

/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their percentage of successful orders.
*/
select * from sellers
select * from order_items
select * from orders
--to check types of order status
select order_status, count(*) from orders
group by 1
----
--Main Join Table
select * from sellers s
join orders o on s.seller_id = o.seller_id
join order_items oi on oi.order_id = o.order_id 
----
---- Find the top 5 sellers based on total sales value:
select seller_name, round(sum(total_price)::numeric,2) as total_revenue from sellers s
join orders o on s.seller_id = o.seller_id
join order_items oi on oi.order_id = o.order_id 
group by 1 order by 2 desc limit 5
---Include both successful and failed orders, and 
---display their percentage of successful orders.
with t1 as (
select seller_name, round(sum(total_price)::numeric,2) as total_revenue from sellers s
join orders o on s.seller_id = o.seller_id
join order_items oi on oi.order_id = o.order_id 
group by 1 order by 2 desc limit 5
),
seller_report as(
select s.seller_name, o.order_status, count(*) as total_orders 
from sellers s
join orders o on s.seller_id = o.seller_id
join order_items oi on oi.order_id = o.order_id 
join t1 t1 on t1.seller_name = s.seller_name
where order_status in ('Completed', 'Returned' , 'Cancelled')
group by 1,2 order by 1,2,3  desc
)
select 
seller_name,
sum(case when order_status = 'Completed' then total_orders else 0 end) as Completed_orders,
sum(case when order_status = 'Cancelled' then total_orders else 0 end ) as Cancelled_orders,
sum(total_orders) as Total_orders,
round(sum(case when order_status = 'Completed' then total_orders else 0 end)::numeric /
sum(total_orders)::numeric * 100, 2)
as percentage_successful_orders
from seller_report
group by 1 order by 5

/*
12. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
*/
SELECT * from products
select * from order_items
---
SELECT 
    p.product_id,
    p.product_name,
    ROUND(
        (SUM(total_price - (p.cogs * oi.quantity))::numeric / SUM(total_price)::numeric) * 100,
        2
    ) AS profit_margin
FROM order_items AS oi
JOIN products AS p ON oi.product_id = p.product_id
GROUP BY 1, 2
ORDER BY 3 DESC;

/*
13. Most Returned Products
Query the top 10 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/
select * from orders
select * from order_items
select * from products
select * from shipping
-----
--Join Tables
select * from orders o
join order_items oi on oi.order_id = o.order_id
join products p on p.product_id = oi.product_id
-----
-- Query: the top 10 products by the number of returns.
select p.product_id, p.product_name, o.order_status, count(o.order_status) as returned_order from orders o
join order_items oi on oi.order_id = o.order_id
join products p on p.product_id = oi.product_id
where order_status = 'Returned'
group by 1,2,3 order by 4 desc limit 10
-----
--Challenge: Display the return rate as a percentage of total units sold for each product.
select 
p.product_id, 
p.product_name, 
count(o.order_status) as total_units_sold,
sum(case when order_status = 'Returned' then 1 else 0 end) as total_returned_units,
round(sum(case when order_status = 'Returned' then 1 else 0 end)::numeric  / count(o.order_status) * 100, 2) as perc
from orders o
join order_items oi on oi.order_id = o.order_id
join products p on p.product_id = oi.product_id
group by 1,2 order by 3 desc limit 10

/*
14. Inactive Sellers
Identify sellers who haven’t made any sales in the last 15 months.
Challenge: Show the last sale date and total sales from those sellers.
*/
select * from sellers
select  * from orders
select * from order_items
----Join Tables ----
select * from sellers s
join orders o on s.seller_id = o.seller_id
----Identify sellers who haven’t made any sales in the last 2 years.
select s.seller_id, s.seller_name
from sellers s
where not exists(
select 1 from orders o 
where s.seller_id = o.seller_id and order_date >= current_date - interval '2 years')
----Challenge: Show the last sale date and total sales from those sellers.
/*with t1 as(
select s.seller_id, s.seller_name
from sellers s
where not exists(
select 1 from orders o 
where s.seller_id = o.seller_id and order_date >= current_date - interval '10 month')
)
select t1.seller_id, t1.seller_name, max(order_date) as last_sale, coalesce(round(sum(oi.total_price)::numeric, 0),0) as total_sales 
from t1 t1
left join orders o on o.seller_id = t1.seller_id
left join order_items oi on o.order_id = oi.order_id
group by 1,2 order by 3 desc
*/

WITH cte1 AS (
    SELECT 
        s.seller_id,
        s.seller_name
    FROM sellers AS s
    WHERE NOT EXISTS (
            SELECT 1 
            FROM orders AS o
            WHERE o.seller_id = s.seller_id 
            AND o.order_date >= CURRENT_DATE - INTERVAL '6 month'
        )
)

SELECT 
    cte1.seller_id,
    cte1.seller_name,
    MAX(o.order_date) AS last_sale_date,
    ROUND(SUM(oi.total_price)::numeric,2) AS total_sales
FROM cte1
LEFT JOIN orders AS o 
    ON cte1.seller_id = o.seller_id
    AND o.order_date < CURRENT_DATE - INTERVAL '6 month'  -- Only historical sales
LEFT JOIN order_items AS oi 
    ON o.order_id = oi.order_id
GROUP BY cte1.seller_id, cte1.seller_name
ORDER BY last_sale_date DESC;
/*
15. IDENTITY customers into returning or new
if the customer has done more than 5 times product returns then categorize them as returning otherwise good
Challenge: List customers id, name, total orders, total returns
*/
select * from customers
select * from orders
select * from shipping
select delivery_status , count(*) from shipping
group by delivery_status

select order_status , count(*) from orders
group by order_status
----Join Table
select * from customers c 
join orders o on o.customer_id = c.customer_id  
join shipping s on s.order_id = o.order_id  
----
with t1 as( 
select 
concat(c.first_name, ' ', c.last_name ) as full_name, 
count(o.order_id) as total_orders,
sum(case when o.order_status = 'Returned' then 1 else 0 end ) as total_return
from customers c
join orders o on o.customer_id = c.customer_id  
join shipping s on s.order_id = o.order_id  
group by 1 order by 3  desc
) 
select * ,  CASE WHEN total_return > 5 THEN 'Returning customer' ELSE 'NEW' END AS customer_category
from t1 
-----
/*
16. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state.
Challenge: Include the number of orders and total sales for each customer.
*/
select * from customers
select * from orders
select * from order_items
-----
select * from customers c 
join orders o on o.customer_id = c.customer_id
join order_items oi on oi.order_id = o.order_id
----Top 5 Customers by Orders in Each State
select concat(c.first_name, ' ' ,c.last_name), count(o.order_id) from customers c 
join orders o on o.customer_id = c.customer_id
join order_items oi on oi.order_id = o.order_id
group by 1 order by 2 desc limit 5 
----Identify the top 5 customers with the highest number of orders for each state.
with t1 as (
select  
state , 
concat(c.first_name, ' ' ,c.last_name) as full_name, 
count(o.order_id) as total_orders,
rank() over(partition by state  order by count(o.order_id) desc) as rank
from customers c 
join orders o on o.customer_id = c.customer_id
join order_items oi on oi.order_id = o.order_id
group by 1,2 order by 1,3 desc
)
select * from t1 where rank <=5 
----Challenge: Include the number of orders and total sales for each customer.
with t1 as (
select  
state , 
concat(c.first_name, ' ' ,c.last_name) as full_name, 
count(o.order_id) as total_orders,
round(sum(total_price)::numeric, 2) as total_sales,
dense_rank() over(partition by state  order by count(o.order_id) desc) as rank
from customers c 
join orders o on o.customer_id = c.customer_id
join order_items oi on oi.order_id = o.order_id
group by 1,2 order by 1,3 desc
)
select * from t1 where rank <=5 
/*
17. Revenue by Shipping Provider
Calculate the total revenue handled by each shipping provider.
Challenge: Include the total number of orders handled and the average return delivery time for each provider.
*/
select * from shipping
select * from orders
select * from order_items
----Join Tables
select * from shipping s
join orders o on s.order_id = o.order_id
join order_items oi on oi.order_id = o.order_id
----Calculate the total revenue handled by each shipping provider:
select shipping_providers, round(sum(total_price)::numeric, 2) as shipping_provider_revenue from shipping s
join orders o on s.order_id = o.order_id
join order_items oi on oi.order_id = o.order_id
group by 1 order by 2 desc
----Include the total number of orders handled and the average delivery time for each provider for rerurn orders.
select 
shipping_providers, 
count(o.order_id) as shipping_provider_orders,
round(sum(oi.total_price)::numeric, 2) as shipping_provider_revenue ,
coalesce (round(avg(return_date- shipping_date)::numeric, 2),0) as avg_days
from shipping s
join orders o on s.order_id = o.order_id
join order_items oi on oi.order_id = o.order_id
where order_status = 'Returned'
group by 1 order by 2 desc

/*
18. Top 10 product with highest decreasing revenue ratio compare to year 2022 and year 2023
Challenge: Return product_id, product_name, category_name, 2022 revenue and 2023 revenue decrease ratio at end Round the result
Note: Decrease ratio = y23-y22/y22* 100
*/
select * from products
select * from categories
select * from orders
select * from order_items
-----Join tables
select * from category c
left join products p on c.category_id = p.category_id
join order_items oi on oi.product_id = p.product_id
join orders o on oi.order_id = o.order_id
---- product_id, product_name, category_name, 2022 revenue
select 
c.category_name,
p.product_id,
p.product_name,
round(sum(oi.total_price)::numeric,2) as total_revenue
from category c
left join products p on c.category_id = p.category_id
join order_items oi on oi.product_id = p.product_id
join orders o on oi.order_id = o.order_id
where extract(year from order_date) = '2022'
group by 1,2,3 order by 4 desc
---- product_id, product_name, category_name, 2023 revenue
select 
c.category_name,
p.product_id,
p.product_name,
round(sum(oi.total_price)::numeric,2) as total_revenue
from category c
left join products p on c.category_id = p.category_id
join order_items oi on oi.product_id = p.product_id
join orders o on oi.order_id = o.order_id
where extract(year from order_date) = '2023'
group by 1,2,3 order by 4 desc
----Top 10 product with highest decreasing revenue ratio compare to year 2022 and year 2023
----Note: Decrease ratio = y23-y22/y22* 100
with t1 as (
select 
c.category_name,
p.product_id,
p.product_name,
round(sum(oi.total_price)::numeric,2) as total_revenue_2022
from category c
left join products p on c.category_id = p.category_id
join order_items oi on oi.product_id = p.product_id
join orders o on oi.order_id = o.order_id
where extract(year from order_date) = '2022'
group by 1,2,3 order by 4 desc
), 
t2 as (
select 
c.category_name,
p.product_id,
p.product_name,
round(sum(oi.total_price)::numeric,2) as total_revenue_2023
from category c
left join products p on c.category_id = p.category_id
join order_items oi on oi.product_id = p.product_id
join orders o on oi.order_id = o.order_id
where extract(year from order_date) = '2023'
group by 1,2,3 order by 4 desc
)
select 
t1.category_name,
t1.product_id,
t1.product_name,
t1.total_revenue_2022,
t2.total_revenue_2023 ,
round((t2.total_revenue_2023 - t1.total_revenue_2022) / t1.total_revenue_2022 * 100, 2) as decrease_ratio
from t1
join t2 on t1.product_id = t2.product_id
order by decrease_ratio
limit 10
